### ISSUE TITLE
Six usage in setup.py prevents install in virtualenv

### ISSUE THREAD

**Issue by JackLeo** [gabrielfalcao/sure#144]
Last (1.4.10) release breaks python 2.7 virtualenv (15.1.0) installs.

```bash
virtualenv env
./env/bin/pip install sure
Collecting sure
  Downloading https://files.pythonhosted.org/packages/b4/63/20dcfbb9ce5e8de5e9377bebee4a80ac0ec431e827d917d5494f58c8ba3f/sure-1.4.10.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 4.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-J5aA4I/sure/setup.py", line 79, in <module>
        version=read_version(),
      File "/tmp/pip-install-J5aA4I/sure/setup.py", line 48, in read_version
        exec(file_data, context)
      File "<string>", line 30, in <module>
    ImportError: No module named six
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-J5aA4I/sure/
```

For the time being, must lock version to 1.4.9

**Comment by barboteur** [comment]
Also happens on python3+.

**Comment by timofurrer** [comment]
@gabrielfalcao How did you build the package for PyPI?
I fail to reproduce this from the current `master` (same for travis).

**Comment by jstephenson** [comment]
I see the same during `pip install`.

**Comment by timofurrer** [comment]
> I see the same during pip install in a venv.

Using the package from PyPI or from local source?

**Comment by frnhr** [comment]
... and if you already happen to have `six` in the virtualenv (I'm using pyenv), then:
```
$ pip install sure
Collecting sure
  Using cached https://files.pythonhosted.org/packages/b4/63/20dcfbb9ce5e8de5e9377bebee4a80ac0ec431e827d917d5494f58c8ba3f/sure-1.4.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s0wE5o/sure/setup.py", line 79, in <module>
        version=read_version(),
      File "/tmp/pip-build-s0wE5o/sure/setup.py", line 48, in read_version
        exec(file_data, context)
      File "<string>", line 33, in <module>
      File "sure/__init__.py", line 33, in <module>
        from sure.old import AssertionHelper
      File "sure/old.py", line 42, in <module>
        from sure.core import DeepComparison
      File "sure/core.py", line 24, in <module>
        from mock.mock import _CallList
    ImportError: No module named mock.mock
```

**Comment by gabrielfalcao** [comment]
I hardcoded the version in setup.py. Reading the version from the source file brought us more trouble than solution, so I'll find a better way to do it later.
