### ISSUE TITLE
1.2.8 have a failed test w/Python 3.4.2

### ISSUE THREAD

**Issue by felixonmars** [gabrielfalcao/sure#71]
Full log:

```
............................E...............................................................................................
======================================================================
ERROR: test_assertion_builder.test_throw_matching_regex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sure/src/sure-1.2.8/sure/old.py", line 125, in raises
    self._src(*self._callable_args, **self._callable_kw)
  File "/build/python-sure/src/sure-1.2.8/tests/test_assertion_builder.py", line 639, in blah
    raise ValueError(msg)
ValueError: this message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/build/python-sure/src/sure-1.2.8/tests/test_assertion_builder.py", line 647, in test_throw_matching_regex
    expect(blah).when.called_with(1).should.throw(re.compile(r'invalid regex'))
  File "/build/python-sure/src/sure-1.2.8/sure/__init__.py", line 377, in wrapper
    value = func(self, *args, **kw)
  File "/build/python-sure/src/sure-1.2.8/sure/__init__.py", line 804, in throw
    return _that.raises(*args, **kw)
  File "/build/python-sure/src/sure-1.2.8/sure/old.py", line 154, in raises
    'Expected to match regex: %r\n against:\n %r' % (identify_callable_location(self._src), msg.pattern, err))
  File "/build/python-sure/src/sure-1.2.8/sure/old.py", line 45, in identify_callable_location
    filename = os.path.relpath(callable_object.func_code.co_filename)
AttributeError: 'function' object has no attribute 'func_code'

----------------------------------------------------------------------
Ran 124 tests in 0.763s

FAILED (errors=1)
```

**Comment by domenkozar** [comment]
Works now on 1.2.24, I have local changes for Nixpkgs

**Comment by timofurrer** [comment]
Seems to be fixed.

Testsuite is running fine on python 2.7, 3.4 and 3.5.
